FROM registry.fedoraproject.org/fedora:latest

# install cloudflare client
RUN dnf install -y \
        systemd \
        dbus-libs \
    && curl -fsSl https://pkg.cloudflareclient.com/cloudflare-warp-ascii.repo | tee /etc/yum.repos.d/cloudflare-warp.repo \
    && sudo dnf install -y \
        cloudflare-warp \
    && dnf clean all \
    && rm -rf /var/cache/yum

ENTRYPOINT ["/sbin/init"]
