FROM debian:bookworm-slim

RUN apt-get update \
    && apt-get install -y \
        ca-certificates \
        iptables \
        iproute2 \
        procps \
        inotify-tools \
        systemd \
        systemd-sysv \  
        sudo \
        curl \
        gpg \
    && curl https://pkg.cloudflareclient.com/pubkey.gpg | sudo gpg --yes --dearmor --output /usr/share/keyrings/cloudflare-warp-archive-keyring.gpg \
    && echo "deb [arch=amd64 signed-by=/usr/share/keyrings/cloudflare-warp-archive-keyring.gpg] https://pkg.cloudflareclient.com/ bookworm main" | sudo tee /etc/apt/sources.list.d/cloudflare-client.list \
    && apt-get update \
    && apt-get install -y \
        cloudflare-warp \
    && export SUDO_FORCE_REMOVE=yes \
    && apt-get remove -y \
        sudo \
        curl \
        gpg \
    && apt -y autoremove

ENTRYPOINT ["/sbin/init"]
